spring.application.name=redbookCopy

spring.datasource.url=jdbc:mysql://localhost:3306/redbookCopy?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Nc!19690628

spring.jpa.hibernate.ddl-auto=update
