spring.application.name=Mongo-blog
spring.data.mongodb.uri=mongodb+srv://wuxiaorc:Nc!19690628@cluster1.7xlfltk.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1
spring.data.mongodb.database=posts

