spring.application.name=SpringSecurity

# Enable HTTPS
server.port=443
server.ssl.key-store=classpath:keystore/selfsigned.jks
server.ssl.key-store-password=password
server.ssl.key-store-type=JKS
server.ssl.key-alias=selfsigned